<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUq6bAEa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUq6bAEa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUq6bAEa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUq6bAEa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUq6bAEa\App_KernelDevDebugContainer([
    'container.build_hash' => 'Uq6bAEa',
    'container.build_id' => 'a9f6a554',
    'container.build_time' => 1652463286,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUq6bAEa');
