<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDYgxtYV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDYgxtYV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDYgxtYV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDYgxtYV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDYgxtYV\App_KernelDevDebugContainer([
    'container.build_hash' => 'DYgxtYV',
    'container.build_id' => '038eee97',
    'container.build_time' => 1659790045,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDYgxtYV');
