<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWjykW5b\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWjykW5b/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWjykW5b.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWjykW5b\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWjykW5b\App_KernelDevDebugContainer([
    'container.build_hash' => 'WjykW5b',
    'container.build_id' => 'fb9ca5b5',
    'container.build_time' => 1655710493,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWjykW5b');
